In [1]:
import pandas as pd
import numpy as np

In [4]:
DATA_PATH = "../datasets/tos_dr/"

#### Cases

Cases refer to individual legal cases or specific issues related to the terms of service or privacy policies of a particular online service. Each case typically focuses on a specific aspect of a service's terms, such as data collection, user rights, content ownership, or security practices.

- id, a unique id for each case (incremental).
- classification, one of those values (good, bad, neutral, blocker).
- score, values range between 0 to 100.
- title.
- description.
- topic_id, connecting the case with it's topic.
- created_at.
- updated_at.
- privacy_related, a flag indicate if it's related to privacy or not.
- docbot_regex, the regex expression used to check for specific words in the quoted text.

In [14]:
tos_cases = pd.read_csv(DATA_PATH + "cases.csv")
tos_cases.head()

,id,classification,score,title,description,topic_id,created_at,updated_at,privacy_related,docbot_regex
0,175,good,50,You can delete your content from this service,You can ask the service to remove your content...,45,2018-01-16 15:26:09.45258,2021-02-27 14:23:56.238878,NaN,NaN
1,130,bad,50,A license is kept on user-generated content ev...,The service may still use your content and dis...,30,2018-01-16 15:26:08.38805,2021-05-06 08:26:06.196896,True,NaN
2,129,bad,60,This service tracks you on other websites,The service may use tracking technologies in t...,25,2018-01-16 15:26:08.370367,2021-02-24 22:56:35.859683,True,NaN
3,237,neutral,0,You agree to comply with the law of the servic...,"By using the service, you agree to comply with...",28,2018-07-22 09:09:08.496243,2021-05-06 08:35:07.855459,NaN,NaN
4,173,bad,25,This service retains rights to your content ev...,The service may still use your content and dis...,45,2018-01-16 15:26:09.415729,2021-02-27 15:51:22.50162,NaN,NaN

#### Topics

Topics are general categories or themes that encompass various cases. They help organize and group similar cases together based on the type of issues they address. For example, "Data Collection" could be a topic that includes cases related to how a service collects and uses user data.

- id, a unique id for each topic (incremental).
- title.
- subtitle, small description.
- description.
- created_at.
- updated_at.

In [ ]:
tos_topics = pd.read_csv(DATA_PATH + "topics.csv")
tos_topics.head()

,id,title,subtitle,description,created_at,updated_at
0,27,Ownership,What happens with the content you generate on ...,The content and the data you generate on servi...,2018-01-16 15:26:04.444207,2018-01-16 15:26:04.444207
1,31,Governance,Your relationship with the service and the com...,description,2018-01-16 15:26:04.535299,2018-01-16 15:26:04.535299
2,32,Guarantee,Some services will guarantee you certain featu...,description,2018-01-16 15:26:04.551182,2018-01-16 15:26:04.551182
3,35,User Involvement in Changing Terms,Are changes proposed as a request for feedback...,"The terms are a contract between two parties, ...",2018-01-16 15:26:04.629039,2018-01-16 15:26:04.629039
4,38,Changes,Changes to the Terms,description,2018-01-16 15:26:04.682205,2018-01-16 15:26:04.682205

#### Services

Services represent specific online platforms, websites, or applications that have their own terms of service and privacy policies.

- id, a unique id for each service (incremental).
- name.
- url.
- created_at.
- updated_at.
- wikipedia, wikipedia url of the service.
- keywords.
- related, connecting the service with one of known similar services in the same field.
- slug. extracted from the name, small letters, no spaces and so on.
- is_comprehensively_reviewed, a flag indicate if it's comprehensively_reviewed or not.
- rating, overall rating for the service based on the all cases.
- status, indicate if the service is deleted or not (deleted, NaN).

In [8]:
tos_services = pd.read_csv(DATA_PATH + "services.csv")
tos_services.head()

,id,name,url,created_at,updated_at,wikipedia,keywords,related,slug,is_comprehensively_reviewed,rating,status
0,440,pebble,pebble.com,2018-05-08 12:19:44.833708,2021-03-25 03:19:30.208894,NaN,NaN,NaN,pebble,False,NaN,NaN
1,353,Yammer,yammer.com,2018-05-08 12:19:43.120991,2021-03-31 01:04:42.63077,https://en.wikipedia.org/wiki/Yammer,NaN,NaN,yammer,False,NaN,NaN
2,2894,Instapaper,instapaper.com,2021-03-29 17:44:07.407582,2021-03-30 00:01:55.169887,https://en.wikipedia.org/wiki/Instapaper,NaN,NaN,instapaper,False,NaN,NaN
3,3157,UNRIC,unric.org,2021-04-16 20:31:05.868802,2021-04-17 00:00:48.616753,NaN,NaN,NaN,unric,False,NaN,NaN
4,162,Infinity,"infinity.com,comcast.com",2018-01-16 15:26:05.072526,2021-03-25 03:19:37.306995,https://en.wikipedia.org/wiki/Infinity#Branding,NaN,NaN,infinity,False,NaN,NaN

#### Points

Points are individual statements or aspects within a case that highlight important information about a service's terms of service or privacy policy. These points can be positive (e.g., strong privacy protections) or negative (e.g., data sharing with third parties).

- id, a unique id for each point (incremental).
- rank, all values are zero.
- title, mostly it's similar to case title.
- source, url of the source.
- status, one of those values (approved, declined, pending, changes-requested, disputed, draft).
- analysis.
- created_at.
- updated_at.
- service_id, connecting the point with it's service.
- quote_text, quotted text from the source which contain information for this point.
- case_id, connecting the point with the related case.
- old_id, used for data migration.
- quote_start, index of first letter of the quotted text in the document.
- quote_end, index of last letter of the quotted text in the document.
- service_needs_rating_update, all values are False.
- document_id, connecting the point with the related document.
- annotation_ref.

In [7]:
tos_points = pd.read_csv(DATA_PATH + "points.csv")
tos_points.head()

,id,rank,title,source,status,analysis,created_at,updated_at,service_id,quote_text,case_id,old_id,point_change,quote_start,quote_end,service_needs_rating_update,document_id,annotation_ref
0,4613,0,No need to register,https://rationalwiki.org/wiki/RationalWiki:Pri...,declined,There is no need to register to view or edit c...,2018-09-08 19:35:01.268707,2021-01-30 13:14:55.558818,702,NaN,320,NaN,NaN,NaN,NaN,False,NaN,NaN
1,605,0,The terms for this service are easy to read,https://groups.google.com/d/topic/tosdr/k_RmZY...,declined,Grammarly's Privacy Policy is easy to read. It...,2018-01-16 15:26:18.500569,2018-10-21 09:44:31.745032,277,NaN,199,k_RmZYGkrww,"For me, the terms of service are still long an...",NaN,NaN,False,NaN,NaN
2,7158,0,The terms for this service are easy to read,https://hp-67.com/terms.html,approved,"The Terms of Service states ""HP-67.com terms o...",2019-06-24 20:13:27.240822,2019-06-25 20:12:34.0269,1675,NaN,199,NaN,NaN,NaN,NaN,False,NaN,NaN
3,4612,0,The service provides two factor authentificati...,https://blog.seznam.cz/2018/04/seznam-cz-ma-no...,declined,The service provides two-factor authentificati...,2018-09-08 19:10:58.633819,2021-02-06 03:50:37.204911,684,NaN,312,NaN,NaN,NaN,NaN,False,NaN,NaN
4,4961,0,The service provides information about how the...,https://www.webseodesigners.com/,declined,Generated through the annotate view,2018-11-10 11:29:57.873485,2021-02-13 00:00:46.903004,820,We use this information to make a business pro...,227,NaN,NaN,10821.0,10880.0,False,725.0,NaN

#### Documents

Documents refer to the original terms of service and privacy policies of the services that are being analyzed on TOSDR. These documents are the source of information for the cases, points, and ratings provided on the platform. TOSDR links to the actual documents, so users can review the full details if they choose to.

- id, a unique id for each document (incremental).
- name, name of document like privacy policy or cookies policy, etc.
- url, url of the document.
- xpath.
- text, the actual document.
- created_at.
- updated_at.
- service_id, connecting the document with it's service.
- reviewed, a flag indicate if the document has been reviewed or not.
- status, indicate if the service is deleted or not (deleted, NaN).
- crawler_server, the server used to crawl the document

In [ ]:
tos_documents = pd.read_csv(DATA_PATH + "documents.csv")

,id,name,url,xpath,text,created_at,updated_at,service_id,reviewed,status,crawler_server
0,1149,social.privacytools.io Privacy Policy,https://social.privacytools.io/terms,/html/body/div/div[2]/div/div[1]/div,\nPrivacy <p>Please review our privacy stateme...,2019-04-06 02:39:01.465351,2020-12-14 19:29:56.243824,1472,NaN,NaN,NaN
1,3719,Privacy Policy,https://www.savvasrealize.com/privacy/corporat...,/html/body/main/div/section/div/div/div[1],Privacy Policy We recently updated our Privac...,2021-01-21 11:15:08.988939,2021-01-24 08:49:24.411559,2619,NaN,NaN,NaN
2,7,Terms of Service,https://help.habbo.com/hc/en-us/articles/22164...,//div[@class='content-body article-body'],<p>\n<strong>Habbo.com - Terms of Service</st...,2018-07-17 10:11:40.691179,2020-12-11 14:20:59.218294,292,True,NaN,NaN
3,9,Terms of Service,https://500px.com/terms,//body,You need to enable JavaScript to run this app....,2018-07-17 10:11:40.759351,2021-03-30 21:11:14.01763,282,True,NaN,eu
4,1319,HERE Cookie Policy,https://legal.here.com/en-gb/privacy/cookies,/html/body/div[1]/div/div,HERE Cookie Policy Effective date:&nbsp;15/07...,2019-05-15 01:44:06.567469,2020-12-14 19:31:28.232051,1559,NaN,NaN,NaN

In [16]:
tos_documents.head()

,id,name,url,xpath,text,created_at,updated_at,service_id,reviewed,status,crawler_server
0,1149,social.privacytools.io Privacy Policy,https://social.privacytools.io/terms,/html/body/div/div[2]/div/div[1]/div,\nPrivacy <p>Please review our privacy stateme...,2019-04-06 02:39:01.465351,2020-12-14 19:29:56.243824,1472,NaN,NaN,NaN
1,3719,Privacy Policy,https://www.savvasrealize.com/privacy/corporat...,/html/body/main/div/section/div/div/div[1],Privacy Policy We recently updated our Privac...,2021-01-21 11:15:08.988939,2021-01-24 08:49:24.411559,2619,NaN,NaN,NaN
2,7,Terms of Service,https://help.habbo.com/hc/en-us/articles/22164...,//div[@class='content-body article-body'],<p>\n<strong>Habbo.com - Terms of Service</st...,2018-07-17 10:11:40.691179,2020-12-11 14:20:59.218294,292,True,NaN,NaN
3,9,Terms of Service,https://500px.com/terms,//body,You need to enable JavaScript to run this app....,2018-07-17 10:11:40.759351,2021-03-30 21:11:14.01763,282,True,NaN,eu
4,1319,HERE Cookie Policy,https://legal.here.com/en-gb/privacy/cookies,/html/body/div[1]/div/div,HERE Cookie Policy Effective date:&nbsp;15/07...,2019-05-15 01:44:06.567469,2020-12-14 19:31:28.232051,1559,NaN,NaN,NaN

## TODO:
- explore the doucments csv more and check if i can find a good one for example (facebook,instagram, etc.)
- hard code a single tos document lang. use an existing one in there and follow their format